server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  profiles:
    active: local
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        column_ordering_strategy: legacy
        jdbc:
#          time_zone: UTC
    hibernate:
#      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
